### ISSUE TITLE
CI Failure on Ruby 3.1: Bundler Frozen Lockfile Prevents Updating Gems

### ISSUE THREAD

**Issue by ahmedmelhady7** [ahmedmelhady7/dirfy#4]
**Summary:**
Our GitHub Actions CI (`build-and-test` job) is failing on Ruby 3.1 with Bundler error code 16. The error indicates that some path-based gemspecs have changed, but Bundler cannot update the `Gemfile.lock` because it is running in frozen mode.

**Reproduction Steps:**

1. Push code (or open a pull request) targeting the `main` branch.
2. The workflow (`.github/workflows/ruby.yml`) starts a job matrix for Ruby 2.7, 3.0, and 3.1.
3. On the Ruby 3.1 runner, the setup step pins Bundler to `2.4.13` and enables `bundler-cache`.
4. During the “Install dependencies” step, the command `bundle install --jobs 4 --retry 3` is executed.
5. Bundler detects that one or more path-based gems have updated their gemspecs, but cannot write these changes to `Gemfile.lock` due to frozen mode.

**Actual Behavior:**

```
The gemspecs for path gems changed, but the lockfile can't be updated because 
frozen mode is set

Run `bundle install` elsewhere and add the updated Gemfile.lock to version 
control.

If this is a development machine, remove the Gemfile.lock freeze by running 
`bundle config set frozen false`.
Error: The process '/opt/hostedtoolcache/Ruby/3.1.7/x64/bin/bundle' failed 
with exit code 16
```

This immediately aborts the CI job on Ruby 3.1, while the same workflow succeeds on Ruby 2.7 and 3.0.

**Expected Behavior:**

* The CI should install all dependencies successfully on Ruby 3.1 without requiring manual intervention.
* If underlying path gems have updated their gemspecs, the workflow should either:

  1. Automatically update and commit the revised `Gemfile.lock` before running `bundle install`, or
  2. Disable frozen mode in CI so that `/bundle install` can regenerate the lockfile on the runner.

**Environment:**

* **OS:** `ubuntu-latest` (GitHub Actions hosted runner)
* **Ruby versions tested:** 2.7, 3.0, 3.1
* **Bundler version:** 2.4.13
* **Workflow file:** `.github/workflows/ruby.yml`

  ```yaml
  name: Ruby CI

  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]

  jobs:
    build-and-test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          ruby: [2.7, 3.0, 3.1]

      steps:
        - uses: actions/checkout@v3
        - name: Set up Ruby (and pin Bundler for Ruby < 3.0)
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: ${{ matrix.ruby }}
            bundler: 2.4.13
            bundler-cache: true

        - name: Install dependencies
          run: bundle install --jobs 4 --retry 3

        - name: Run specs
          run: bundle exec rake spec
  ```

**Possible Solutions:**

1. **Update and Commit `Gemfile.lock`:**

   * On a local machine (or separate branch), run:

     ```bash
     bundle install
     git add Gemfile.lock
     git commit -m "Update Gemfile.lock for changed path gems"
     git push
     ```
   * This ensures the CI runner has an up-to-date lockfile, preventing the frozen-mode error.

2. **Disable Frozen Mode in CI:**

   * Modify the “Install dependencies” step in `ruby.yml` to unset frozen mode before running `bundle install`. For example:

     ```yaml
     - name: Install dependencies
       run: |
         bundle config set frozen false
         bundle install --jobs 4 --retry 3
     ```
   * This allows Bundler on the CI runner to overwrite `Gemfile.lock` if necessary. Note that this may introduce unintended lockfile changes in CI; ideally, you should still commit any legitimate updates locally.

3. **Pin Path Gems to Specific Commits or Versions:**

   * If you’re using path-based gems (e.g., `gem "my_gem", path: "../my_gem"`), consider switching to a Git reference or published gem version so that Bundler will not see gemspec changes unless you explicitly update. For example:

     ```ruby
     gem "my_gem", git: "https://github.com/your_org/my_gem.git", tag: "v1.2.3"
     ```

---

**Additional Context:**

* Because only the Ruby 3.1 matrix entry is failing, it suggests that one of the path-based gems may have a minor incompatibility or changed metadata that Bundler 2.4.13 enforces more strictly.
* If you have multiple maintainers, ensure everyone runs `bundle install` locally after pulling the latest commits to avoid future “frozen” lockfile issues.
* Once the lockfile is updated and pushed, the CI should succeed on Ruby 3.1 without any further changes.
